### ISSUE TITLE
examples/otool is broken

### ISSUE THREAD

**Issue by codido** [flier/rust-macho#13]
memmap's api slightly changed (Protection, Mmap::open_path() and Mmap::as_slice() were removed), so otool no longer builds properly.

**Comment by flier** [comment]
[fixed](https://github.com/flier/rust-macho/commit/34689b5cea876a21e1f8a71f33bafad7bd2f2d7d), thanks for your reports :)

**Comment by codido** [comment]
Thanks!
However, seems the commit following it (update of env_logger) broke it again:
```
error[E0599]: no method named `unwrap` found for type `()` in the current scope
  --> examples/otool.rs:34:24
   |
34 |     env_logger::init().unwrap();
   |                        ^^^^^^
```

**Comment by flier** [comment]
oops, I missed it, thanks again
