### ISSUE TITLE
LC_DYLD_INFO should be handled similarly to LC_DYLD_INFO_ONLY

### ISSUE THREAD

**Issue by codido** [flier/rust-macho#14]
Seems the two share the same structure, so perhaps they should be handled similarly in LoadCommand::parse() by adding an extra (boolean) field to LoadCommand::DyldInfo?

**Comment by flier** [comment]
Yes, it should [share same command structure](https://opensource.apple.com/source/ld64/ld64-274.2/src/other/dyldinfo.cpp.auto.html), it could [be parsed like LC_DYLD_INFO_ONLY](https://github.com/flier/rust-macho/commit/f2ca6b8663cda1a17e976206a095ed62e8e08b30), let me dig more detail about it later.

**Comment by flier** [comment]
The `LoadCommand::DyldInfo` command was parsed as [an iterator of symbol](https://github.com/flier/rust-macho/blob/feature/bind-info/examples/otool.rs#L358)

**Comment by codido** [comment]
@flier While looking at the code you linked, the addition there caught my eyes - since a wrapping addition isn't used, a large enough bind_off may result in a panic due to an integer overflow. It appears this isn't the only place where this happens.

This probably warrants a separate ticket..

**Comment by flier** [comment]
Thanks @codido, I think convert it to usize before add will be better.

**Comment by codido** [comment]
usize might be the same size as u32 on 32bit systems, no? Not that there are too many of these nowadays :)

**Comment by codido** [comment]
also, unless I'm missing something, if start > end, I believe that would result in a panic as well when slicing [start..end]

**Comment by flier** [comment]
I guess the `start` will never larger than `end`, because

```rust
                        let start = bind_off as usize;
                        let end = bind_off
                            .checked_add(bind_size)
                            .ok_or(MachError::BufferOverflow(bind_size as usize))?
                            as usize;
```

**Comment by codido** [comment]
Sure thing :)

**Comment by flier** [comment]
I have extracted those check to a `CheckedSlice` trait, @codido

**Comment by codido** [comment]
@flier Sounds good, though wouldn't MachError::BufferOverflow(off + len) panic when adding off to len in this case?

**Comment by flier** [comment]
In theory, yes, although all the offset/size in Mach-O file is a `off_t/u32` type, anyway, I fix it

**Comment by codido** [comment]
Thanks for all the fixes, @flier!

**Comment by flier** [comment]
You are welcome :)
