### ISSUE TITLE
cmdsize isn't checked before resizing payload

### ISSUE THREAD

**Issue by codido** [flier/rust-macho#16]
In LoadCommand::parse(), before resizing payload, it might be a good idea to verify that buf has enough bytes to read from. Otherwise, parsing an invalid binary may result in an OOM crash.

**Comment by flier** [comment]
anything else I missed?

**Comment by codido** [comment]
@flier The payload resizing for the default case of unhandled commands (LoadCommand::parse()) is unprotected, so this could still result in an OOM for invalid binaries.

**Comment by flier** [comment]
thanks @codido, more check has been added
