### ISSUE TITLE
Possible infinite recursion when parsing fat files

### ISSUE THREAD

**Issue by codido** [flier/rust-macho#18]
OFile::parse can call OFile::parse_fat_file, which in turn calls OFile::parse back.
Since the offsets aren't verified, it is possible to get into an infinite recursion (e.g. if the offset is 0), exceeding the maximal size of the stack.

This can be triggered by some java .class files which happen to share the same magic number.

**Comment by flier** [comment]
can you give some example .class file?

**Comment by flier** [comment]
it seems the JAVA [.class file format](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html) is totally different to the [FAT file format](https://opensource.apple.com/source/xnu/xnu-344/EXTERNAL_HEADERS/mach-o/fat.h), it only use same magic word :(

**Comment by flier** [comment]
anyway, we can check whether the offset out of range, please check with v0.1.10

**Comment by codido** [comment]
@flier Seems to work, thanks!
