### ISSUE TITLE
Failure on AR Parsing

### ISSUE THREAD

**Issue by mitsuhiko** [flier/rust-macho#7]
I encountered a macho file that does not parse correctly. It eventually falls over here:

```
DEBUG:mach_object::loader: parsed 5 load commands
DEBUG:mach_object::loader: 0x0001075c	seek to 0x0001638c, skip 23600 bytes
DEBUG:mach_object::loader: 0x0001638c	parsing ar header
```

When you look where it tries to parse an `ArHeader` you can see that the cursor points to the ar magic (`!<arch>\n`) which it should already have skipped past.  I tried to understand the flow of the parser here but I'm not entirely sure how those headers are supposed to be skipped.

I attached the failing file.

[libH5.a.zip](https://github.com/flier/rust-macho/files/815411/libH5.a.zip)

**Comment by mitsuhiko** [comment]
I should clarify that it ultimately falls over trying to parse integers out of the garbage it reads by not being put after the header.  So the error you will actually see is something like "parse int error: invalid digit found in string" where what's actually happening is that it tries to parse `100644  24` or something like this into an integer.

**Comment by flier** [comment]
Thanks for reporting the issue, seems caused by a fat header with multi archs

**Comment by mitsuhiko** [comment]
Thanks so much for fixing this!

**Comment by flier** [comment]
You are welcome :)
