### ISSUE TITLE
Consider switching API to Cursor<T>

### ISSUE THREAD

**Issue by mitsuhiko** [flier/rust-macho#8]
Would you be interested in a PR that changes the interface to accept a `Cursor<T>` rather than the current cursor over a slice? It would make it easier to work with a `Vec<u8>` or similar. I currently have to do some not so nice workarounds with memory management in the context of iterators to support the current `&mut[u8]` cursor.

**Comment by flier** [comment]
Sure, I use `Cursor<&[u8]>` because it matched my requirements (memmap), if you need more general `Cursor<T>`, please go ahead. :)
